#!/bin/bash
{
    echo
    herbstclient --idle '((window_title|focus)_changed)|tag_flags'
} |
while read line; do
    herbstclient dump
done | perl -ne '$| = 1; print join(" ", m/0x[\da-f]+/g) . "\n"'
